- id: duolingo
  name: Duolingo
  entry: duolingo/pre-commit-hooks:1.11.0 /entry
  language: docker_image
  types: [text]

- id: sync-ai-rules
  name: Sync AI Rules
  entry: duolingo/pre-commit-hooks:1.11.0 sh -c "PYTHONPATH=/ python3 -m sync_ai_rules"
  language: docker_image
  files: &sync_ai_rules_files ^\.cursor/rules/.*\.mdc$
  pass_filenames: false

# Nobody should ever use these hooks in production. They're just for testing PRs in
# the duolingo/pre-commit-hooks repo more easily without having to tag and push
# temporary images to Docker Hub. Usage: edit a consumer repo's hook config to
# instead declare `id: duolingo-dev` or `id: sync-ai-rules-dev` and `rev: <PR branch SHA>`,
# then run `pre-commit run <hook-id> --all-files`
- id: duolingo-dev
  name: Duolingo (dev)
  entry: /entry
  language: docker
  types: [text]

- id: sync-ai-rules-dev
  name: Sync AI Rules (dev)
  entry: sh -c "PYTHONPATH=/ python3 -m sync_ai_rules"
  language: docker
  files: *sync_ai_rules_files
  pass_filenames: false
