repos:
  - repo: .
    rev: 1.9.0
    hooks:
      - id: duolingo
        exclude: test/
  - repo: local
    hooks:
      - id: test
        name: Tests
        entry: make test
        language: system
        pass_filenames: false
