cache-dir = "/tmp/.cache/ruff"
fix-only = true
line-length = 100
target-version = "py37"

[pydocstyle]
convention = "pep257"

[isort]
combine-as-imports = true

[lint]
# https://docs.astral.sh/ruff/rules/
select = [
  "B",
  "C4",
  "D",
  "E",
  "F",
  "I",
  "ISC",
  "PERF",
  "PIE",
  "PL",
  "Q",
  "RUF",
  "SIM",
  "UP",
]
