#!/usr/bin/env python3
"""
This script uses a plugin architecture to parse rules and generate documentation.
"""

import logging
import os
import subprocess
from pathlib import Path
from typing import Dict, List

logger = logging.getLogger(__name__)

from sync_ai_rules.core.plugin_manager import PluginManager
from sync_ai_rules.core.rule_metadata import RuleMetadata
from sync_ai_rules.file_updater import update_documentation_file


def get_category(file_path: str, source_dir: str) -> str:
    """Extract category from file path relative to source directory."""
    rel_path = os.path.relpath(file_path, source_dir)
    folder = os.path.dirname(rel_path)
    return folder if folder and folder != "." else "root"


def group_by_category(rules: List[RuleMetadata]) -> Dict[str, List[RuleMetadata]]:
    """Group rules by category."""
    groups: Dict[str, List[RuleMetadata]] = {}
    for rule in rules:
        groups.setdefault(rule.category, []).append(rule)
    return groups


def scan_and_parse(parser, source_dir: str, project_root: str) -> List[RuleMetadata]:
    """Scan directory and parse files with given parser."""
    rules = []

    if not os.path.exists(source_dir):
        return rules

    for root, _, files in os.walk(source_dir):
        # Skip generated/personal directories
        if "generated" in Path(root).parts or "personal" in Path(root).parts:
            continue

        for file in files:
            file_path = os.path.join(root, file)

            if not parser.can_parse(file_path):
                continue

            context = {
                "project_root": project_root,
                "relative_path": os.path.relpath(file_path, project_root),
                "category": get_category(file_path, source_dir),
            }

            rule = parser.parse(file_path, context)
            if rule:
                rules.append(rule)

    return rules


def _write_gitattributes(directory: str, filenames: List[str]) -> None:
    """Write .gitattributes to hide generated files from GitHub PR diffs."""
    os.makedirs(directory, exist_ok=True)
    path = os.path.join(directory, ".gitattributes")
    with open(path, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by sync-ai-rules hook. Do not edit.\n")
        for name in filenames:
            f.write(f"{name} linguist-generated\n")


def _ensure_agents_skills_symlinks(project_root: str) -> None:
    """Create .claude/skills -> .agents/skills wherever .agents/skills/ exists."""
    for dirpath, _, _ in os.walk(project_root):
        agents_dir = os.path.join(dirpath, ".agents", "skills")
        if not os.path.isdir(agents_dir):
            continue

        claude_dir = os.path.join(dirpath, ".claude")
        symlink_path = os.path.join(claude_dir, "skills")
        # Relative target: .claude/skills -> ../.agents/skills
        target = os.path.join("..", ".agents", "skills")

        if os.path.islink(symlink_path) or os.path.exists(symlink_path):
            continue

        try:
            os.makedirs(claude_dir, exist_ok=True)
            os.symlink(target, symlink_path)
            rel = os.path.relpath(symlink_path, project_root)
            print(f"  ✓ Created symlink: {rel} -> .agents/skills")
        except OSError as e:
            rel = os.path.relpath(dirpath, project_root)
            logger.warning("Failed to create agents skills symlink at %s: %s", rel, e)


_SOURCE_PREFIXES = (".cursor/", ".code_review/", ".agents/")


def _has_relevant_staged_changes() -> bool:
    """Check if any staged files (including deletions) touch source directories."""
    try:
        result = subprocess.run(
            ["git", "diff", "--cached", "--name-only"],
            capture_output=True,
            text=True,
            check=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return True

    return any(line.startswith(_SOURCE_PREFIXES) for line in result.stdout.splitlines())


def main():
    """Main orchestration: load pipelines → parse → generate → update files."""
    if not _has_relevant_staged_changes():
        return

    # Setup
    project_root = str(Path.cwd())
    script_dir = os.path.dirname(os.path.abspath(__file__))

    plugin_manager = PluginManager()
    plugin_manager.load_plugins(script_dir)

    # Process each pipeline
    print()
    for pipeline in plugin_manager.pipelines:
        print(f"Processing pipeline: {pipeline.name}")

        # Scan and parse using pipeline's parser
        all_rules = []
        for rel_dir in pipeline.parser.source_directories:
            source_dir = os.path.join(project_root, rel_dir)
            print(f"  Scanning {rel_dir}...")
            rules = scan_and_parse(pipeline.parser, source_dir, project_root)
            all_rules.extend(rules)

        if not all_rules:
            print("  No rules found, skipping")
            continue

        # Group rules by category
        grouped_rules = group_by_category(all_rules)
        print(f"  Found {len(all_rules)} rules in {len(grouped_rules)} categories")

        # Generate output
        if pipeline.generator.is_multi_file:
            pipeline.generator.generate_files(grouped_rules, project_root)
        else:
            content = pipeline.generator.generate(grouped_rules, {})
            for filename in pipeline.generator.default_filenames:
                file_path = os.path.join(project_root, filename)
                success, message = update_documentation_file(
                    file_path, content, pipeline.generator.get_section_markers()
                )
                status = "✓" if success else "✗"
                print(f"  {status} {message}")

    # Write .gitattributes in non-root output directories
    output_dirs: Dict[str, List[str]] = {}
    for pipeline in plugin_manager.pipelines:
        if pipeline.generator.is_multi_file:
            continue
        for filename in pipeline.generator.default_filenames:
            parent = os.path.dirname(filename)
            if parent:
                output_dirs.setdefault(parent, []).append(os.path.basename(filename))

    for dir_path, filenames in output_dirs.items():
        _write_gitattributes(os.path.join(project_root, dir_path), sorted(set(filenames)))

    # Create symlinks so Claude Code can discover skills from .agents/skills/
    _ensure_agents_skills_symlinks(project_root)

    print("\n✓ Rules synchronization completed!")


if __name__ == "__main__":
    main()
