#!/usr/bin/env python3
"""
Claude Rules Generator - generates Claude Code rules from .cursor/rules/.
Each rule becomes a separate .md file in .claude/rules/generated/,
with optional paths frontmatter for file-scoped activation.
"""

import logging
import os
import re
import shutil
from typing import Any, Dict, List

from sync_ai_rules.core.generator_interface import OutputGenerator
from sync_ai_rules.core.rule_metadata import RuleMetadata

_RULES_DIR = ".claude/rules/generated"
_SOURCE_DIR = ".cursor/rules"

logger = logging.getLogger(__name__)


class ClaudeRulesGenerator(OutputGenerator):
    """Generate Claude Code path-scoped rules from cursor rules."""

    @property
    def name(self) -> str:
        return "claude-rules"

    @property
    def default_filenames(self) -> List[str]:
        return [_RULES_DIR]

    def generate(self, rules: Dict[str, List[RuleMetadata]], config: Dict[str, Any]) -> str:
        total = sum(len(r) for r in rules.values())
        return f"Generated {total} Claude rules in {len(rules)} categories"

    @property
    def is_multi_file(self) -> bool:
        return True

    def generate_files(self, rules: Dict[str, List[RuleMetadata]], project_root: str) -> None:
        """Generate rule files in .claude/rules/generated/."""
        _remove_legacy_skills(project_root)

        rules_root = os.path.join(project_root, _RULES_DIR)

        # Remove all existing generated files before regenerating
        if os.path.isdir(rules_root):
            for entry in os.listdir(rules_root):
                entry_path = os.path.join(rules_root, entry)
                if entry.endswith(".md") and os.path.isfile(entry_path):
                    os.remove(entry_path)

        os.makedirs(rules_root, exist_ok=True)

        for category_rules in rules.values():
            for rule in category_rules:
                rel_path = _strip_source_prefix(rule.relative_path)
                path_parts = rel_path.replace(os.sep, "/").split("/")
                path_parts[-1] = os.path.splitext(path_parts[-1])[0]
                rule_filename = "-".join(path_parts) + ".md"
                rule_file = os.path.join(rules_root, rule_filename)

                try:
                    content = _format_rule(rule)
                    with open(rule_file, "w", encoding="utf-8") as f:
                        f.write(content)
                    print(f"  ✓ Created rule: {rule_filename}")
                except OSError as e:
                    logger.warning("Failed to write rule %s: %s", rule_filename, e)
                    print(f"  ✗ Failed to create rule: {rule_filename}")

        _write_gitattributes(rules_root)

    def get_section_markers(self) -> tuple[str, str]:
        return ("", "")


def _remove_legacy_skills(project_root: str) -> None:
    """Remove old generated_* skill directories from .claude/skills/."""
    skills_root = os.path.join(project_root, ".claude", "skills")
    if not os.path.isdir(skills_root):
        return
    for entry in os.listdir(skills_root):
        if entry.startswith("generated_") and os.path.isdir(os.path.join(skills_root, entry)):
            shutil.rmtree(os.path.join(skills_root, entry))
            print(f"  ✓ Removed legacy skill: {entry}")


def _write_gitattributes(rules_root: str) -> None:
    """Write .gitattributes to hide generated rules from GitHub PR diffs."""
    path = os.path.join(rules_root, ".gitattributes")
    with open(path, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by sync-ai-rules hook. Do not edit.\n*.md linguist-generated\n")


def _strip_source_prefix(relative_path: str) -> str:
    """Strip the .cursor/rules/ prefix from a rule's relative path."""
    prefix = _SOURCE_DIR + os.sep
    if relative_path.startswith(prefix):
        return relative_path[len(prefix) :]
    prefix_fwd = _SOURCE_DIR + "/"
    if relative_path.startswith(prefix_fwd):
        return relative_path[len(prefix_fwd) :]
    return relative_path


def _format_rule(rule: RuleMetadata) -> str:
    """Format a rule as a Claude Code rule .md file."""
    lines = []

    if rule.scope_patterns:
        lines.append("---")
        lines.append("paths:")
        for pattern in rule.scope_patterns:
            lines.append(f'  - "{pattern}"')
        lines.append("---")
        lines.append("")

    body = _extract_body(rule.raw_content)
    if body:
        lines.append(body)

    return "\n".join(lines) + "\n"


def _extract_body(raw_content: str) -> str:
    """Extract body content from raw rule content (after frontmatter)."""
    match = re.match(r"^---\s*\n.*?\n---\s*\n(.*)$", raw_content, re.DOTALL)
    if match:
        return match.group(1).strip()
    return raw_content.strip()
